export const trails_db = [
	{
		title: 'Lake Tahoe',
		location: 'Tahoe National Forest',
		rate: '⭐⭐⭐⭐',
		reviews: '(246)',
		distance: 'Length: 2.5 mi - Time: 2h 39min',
		image: 'https://picsum.photos/300/300?random?lake',
	},
	{
		title: 'Los Padres',
		location: 'Los Padres National Forest',
		rate: '⭐⭐⭐⭐',
		reviews: '(312)',
		distance: 'Length: 3.2 mi - Time: 2h 45min',
		image: 'https://picsum.photos/300/300?random?hiking',
	},
	{
		title: 'Mount Rainier',
		location: 'Mount Rainier National Park',
		rate: '⭐⭐⭐⭐',
		reviews: '(198)',
		distance: 'Length: 2.8 mi - Time: 2h 36min',
		image: 'https://picsum.photos/300/300?random?forest',
	},
	{
		title: 'Rocky Mountain',
		location: 'Rocky Mountain Forest',
		rate: '⭐⭐⭐⭐',
		reviews: '(189)',
		distance: 'Length: 2.6 mi - Time: 2h 42min',
		image: 'https://picsum.photos/300/300?random?mountain',
	},
	{
		title: 'Grand Canyon',
		location: 'Grand Canyon National Park',
		rate: '⭐⭐⭐⭐',
		reviews: '(365)',
		distance: 'Length: 2.4 mi - Time: 2h 38min',
		image: 'https://picsum.photos/300/300?random?canyon',
	},
	{
		title: 'Olympic',
		location: 'Olympic National Park',
		rate: '⭐⭐⭐⭐',
		reviews: '(277)',
		distance: 'Length: 2.7 mi - Time: 2h 40min',
		image: 'https://picsum.photos/300/300?random?trail',
	},
];
